# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 1x
email: volumedigital@eml.cc
description:
  I use C++ in embedded systems.
  I have ~15 years of experience.
  I am a 1x engineer.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: volumedigital1
github_username:  volumeDigital

# Build settings
markdown: kramdown
